<?php
header('Content-Type: application/json');
echo '[
    {
        "AK_LOT_ID": 14,
        "AK_ID": 86,
        "AK_Name": "Dummy_BioObject_1",
        "HERST_ID": 10,
        "HERST_Name": "Klinik_004",
        "REF_NR": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "LOT_NR": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "KONZ": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "HOST": "Dummy_BioObject_2",
        "ISOTYP": "Dummy_BioObject_3",
        "KLON": "Dummy_BioObject_4",
        "STATUS": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "IST_SEK_ANTIKOERPER": false,
        "upsize_ts": "AAAAAAAlago="
    },
    {
        "AK_LOT_ID": 15,
        "AK_ID": 8,
        "AK_Name": "Dummy_BioObject_5",
        "HERST_ID": 17,
        "HERST_Name": "Klinik_005",
        "REF_NR": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "LOT_NR": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "KONZ": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "HOST": "Dummy_BioObject_2",
        "KLON": "Dummy_BioObject_4",
        "LAGERUNG": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "KONTROLLGEWEBE": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "REAKTIVITAET": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "EIGENTUEMER": "Mitarbeiter_002",
        "STATUS": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "IST_SEK_ANTIKOERPER": false,
        "upsize_ts": "AAAAAAAlaeE="
    },
    {
        "AK_LOT_ID": 16,
        "AK_ID": 82,
        "AK_Name": "Dummy_BioObject_6",
        "HERST_ID": 14,
        "HERST_Name": "Klinik_003",
        "REF_NR": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "LOT_NR": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "KONZ": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "HOST": "Dummy_BioObject_2",
        "KLON": "Dummy_BioObject_4",
        "LAGERUNG": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "STATUS": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "IST_SEK_ANTIKOERPER": true,
        "upsize_ts": "AAAAAAAlafU="
    },
    {
        "AK_LOT_ID": 17,
        "AK_ID": 83,
        "AK_Name": "Dummy_BioObject_7",
        "HERST_ID": 14,
        "HERST_Name": "Klinik_003",
        "REF_NR": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "LOT_NR": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "KONZ": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "HOST": "Dummy_BioObject_8",
        "KLON": "Dummy_BioObject_4",
        "LAGERUNG": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "STATUS": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "IST_SEK_ANTIKOERPER": true,
        "upsize_ts": "AAAAAAAlafQ="
    },
    {
        "AK_LOT_ID": 18,
        "AK_ID": 84,
        "AK_Name": "Dummy_BioObject_9",
        "HERST_ID": 14,
        "HERST_Name": "Klinik_003",
        "REF_NR": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "LOT_NR": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "KONZ": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "HOST": "Dummy_BioObject_2",
        "KLON": "Dummy_BioObject_4",
        "LAGERUNG": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "STATUS": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "IST_SEK_ANTIKOERPER": true,
        "upsize_ts": "AAAAAAAlafY="
    }
]';
