<?php
header('Content-Type: application/json');
echo '[
    {
        "FAERB_ID": 27,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Folgeprojekt": "Anonymisierte_Daten_Dummy",
        "IHC_Schnitte": 6,
        "GEWEBE": "Anonymisierte_Daten_Dummy",
        "IHC_Faerbegeraet": "Anonymisierte_Daten_Dummy",
        "Etablierungslauf": true,
        "Faerbelauftyp": "Anonymisierte_Daten_Dummy",
        "FAERBE_KIT": "Anonymisierte_Daten_Dummy",
        "REG_DATUM": "2016-01-14T00:00:00",
        "DEMASKIERUNG": "Anonymisierte_Daten_Dummy",
        "REAGENZ": "Anonymisierte_Daten_Dummy",
        "VORBEHANDLUNGSZEIT": 10,
        "PRI_AK_ID": 104,
        "PRI_AK_LOT_ID": 139,
        "PRI_AK_NAME": "Anonymisierte_Daten_Dummy",
        "PRI_VERDUENNUNG": "Anonymisierte_Daten_Dummy",
        "PRI_INKUBATIONSZEIT": "Anonymisierte_Daten_Dummy",
        "SEK_AK_ID": 85,
        "SEK_AK_LOT_ID": 112,
        "SEK_AK_NAME": "Anonymisierte_Daten_Dummy",
        "SEK_INKUBATIONSZEIT": "Anonymisierte_Daten_Dummy",
        "OPTI_HQ_LINKER_ZEIT": 8,
        "OPTI_HQ_MULTI_ZEIT": 8,
        "OPTI_PEROXIDASE_HEMMER": "Anonymisierte_Daten_Dummy",
        "BL_H2O2": false,
        "BL_AVIDIN_BIOTIN": false,
        "BL_BSA_NGS": false,
        "MATERIAL": "Anonymisierte_Daten_Dummy",
        "BEMERKUNGEN": "Anonymisierte_Daten_Dummy",
        "TA": "Mitarbeiter_001",
        "NICHT_BERECHNEN": false,
        "upsize_ts": "AAAAAAADv0k="
    },
    {
        "FAERB_ID": 28,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Folgeprojekt": "Anonymisierte_Daten_Dummy",
        "IHC_Schnitte": 6,
        "GEWEBE": "Anonymisierte_Daten_Dummy",
        "IHC_Faerbegeraet": "Anonymisierte_Daten_Dummy",
        "Etablierungslauf": true,
        "Faerbelauftyp": "Anonymisierte_Daten_Dummy",
        "FAERBE_KIT": "Anonymisierte_Daten_Dummy",
        "REG_DATUM": "2015-11-18T00:00:00",
        "DEMASKIERUNG": "Anonymisierte_Daten_Dummy",
        "REAGENZ": "Anonymisierte_Daten_Dummy",
        "VORBEHANDLUNGSZEIT": 10,
        "PRI_AK_ID": 13,
        "PRI_AK_LOT_ID": 25,
        "PRI_AK_NAME": "Anonymisierte_Daten_Dummy",
        "PRI_VERDUENNUNG": "Anonymisierte_Daten_Dummy",
        "PRI_INKUBATIONSZEIT": "Anonymisierte_Daten_Dummy",
        "SEK_AK_ID": 85,
        "SEK_AK_LOT_ID": 112,
        "SEK_AK_NAME": "Anonymisierte_Daten_Dummy",
        "SEK_VERDUENNUNG": "Anonymisierte_Daten_Dummy",
        "SEK_INKUBATIONSZEIT": "Anonymisierte_Daten_Dummy",
        "BL_H2O2": true,
        "BL_AVIDIN_BIOTIN": false,
        "BL_BSA_NGS": false,
        "NICHT_BERECHNEN": false,
        "upsize_ts": "AAAAAAADv0o="
    },
    {
        "FAERB_ID": 29,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Folgeprojekt": "Anonymisierte_Daten_Dummy",
        "IHC_Schnitte": 6,
        "GEWEBE": "Anonymisierte_Daten_Dummy",
        "IHC_Faerbegeraet": "Anonymisierte_Daten_Dummy",
        "Etablierungslauf": true,
        "Faerbelauftyp": "Anonymisierte_Daten_Dummy",
        "FAERBE_KIT": "Anonymisierte_Daten_Dummy",
        "REG_DATUM": "2015-11-23T00:00:00",
        "DEMASKIERUNG": "Anonymisierte_Daten_Dummy",
        "REAGENZ": "Anonymisierte_Daten_Dummy",
        "VORBEHANDLUNGSZEIT": 10,
        "PRI_AK_ID": 13,
        "PRI_AK_LOT_ID": 25,
        "PRI_AK_NAME": "Anonymisierte_Daten_Dummy",
        "PRI_VERDUENNUNG": "Anonymisierte_Daten_Dummy",
        "PRI_INKUBATIONSZEIT": "Anonymisierte_Daten_Dummy",
        "SEK_AK_ID": 85,
        "SEK_AK_LOT_ID": 112,
        "SEK_AK_NAME": "Anonymisierte_Daten_Dummy",
        "SEK_VERDUENNUNG": "Anonymisierte_Daten_Dummy",
        "SEK_INKUBATIONSZEIT": "Anonymisierte_Daten_Dummy",
        "BL_H2O2": true,
        "BL_AVIDIN_BIOTIN": false,
        "BL_BSA_NGS": false,
        "NICHT_BERECHNEN": false,
        "upsize_ts": "AAAAAAADv0s="
    },
    {
        "FAERB_ID": 30,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Folgeprojekt": "Anonymisierte_Daten_Dummy",
        "IHC_Schnitte": 2,
        "GEWEBE": "Anonymisierte_Daten_Dummy",
        "IHC_Faerbegeraet": "Anonymisierte_Daten_Dummy",
        "Etablierungslauf": true,
        "Faerbelauftyp": "Anonymisierte_Daten_Dummy",
        "FAERBE_KIT": "Anonymisierte_Daten_Dummy",
        "REG_DATUM": "2015-11-25T00:00:00",
        "DEMASKIERUNG": "Anonymisierte_Daten_Dummy",
        "REAGENZ": "Anonymisierte_Daten_Dummy",
        "VORBEHANDLUNGSZEIT": 10,
        "PRI_AK_ID": 13,
        "PRI_AK_LOT_ID": 25,
        "PRI_AK_NAME": "Anonymisierte_Daten_Dummy",
        "PRI_VERDUENNUNG": "Anonymisierte_Daten_Dummy",
        "PRI_INKUBATIONSZEIT": "Anonymisierte_Daten_Dummy",
        "SEK_AK_ID": 85,
        "SEK_AK_LOT_ID": 112,
        "SEK_AK_NAME": "Anonymisierte_Daten_Dummy",
        "SEK_VERDUENNUNG": "Anonymisierte_Daten_Dummy",
        "SEK_INKUBATIONSZEIT": "Anonymisierte_Daten_Dummy",
        "BL_H2O2": true,
        "BL_AVIDIN_BIOTIN": false,
        "BL_BSA_NGS": false,
        "NICHT_BERECHNEN": false,
        "upsize_ts": "AAAAAAADv0w="
    },
    {
        "FAERB_ID": 31,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Folgeprojekt": "Anonymisierte_Daten_Dummy",
        "IHC_Schnitte": 4,
        "GEWEBE": "Anonymisierte_Daten_Dummy",
        "IHC_Faerbegeraet": "Anonymisierte_Daten_Dummy",
        "Etablierungslauf": true,
        "Faerbelauftyp": "Anonymisierte_Daten_Dummy",
        "FAERBE_KIT": "Anonymisierte_Daten_Dummy",
        "REG_DATUM": "2015-11-27T00:00:00",
        "DEMASKIERUNG": "Anonymisierte_Daten_Dummy",
        "REAGENZ": "Anonymisierte_Daten_Dummy",
        "VORBEHANDLUNGSZEIT": 64,
        "PRI_AK_ID": 13,
        "PRI_AK_LOT_ID": 25,
        "PRI_AK_NAME": "Anonymisierte_Daten_Dummy",
        "PRI_VERDUENNUNG": "Anonymisierte_Daten_Dummy",
        "PRI_INKUBATIONSZEIT": "Anonymisierte_Daten_Dummy",
        "OPTI_HQ_LINKER_ZEIT": 8,
        "OPTI_HQ_MULTI_ZEIT": 8,
        "OPTI_PEROXIDASE_HEMMER": "Anonymisierte_Daten_Dummy",
        "BL_H2O2": false,
        "BL_AVIDIN_BIOTIN": false,
        "BL_BSA_NGS": false,
        "NICHT_BERECHNEN": false,
        "upsize_ts": "AAAAAAADu2c="
    }
]';
