<?php
header('Content-Type: application/json');
echo '[
  {
    "FAERB_ID": 10020,
    "ProjektNr": "1842",
    "Folgeprojekt": "",
    "IHC_Schnitte": 6,
    "GEWEBE": "Prostata",
    "IHC_Faerbegeraet": "Dako",
    "Etablierungslauf": true,
    "Faerbelauftyp": "Testlauf",
    "FAERBE_KIT": "Dako Real AEC",
    "REG_DATUM": "2021-01-14T00:00:00",
    "DEMASKIERUNG": "HIER",
    "REAGENZ": "Dako pH6",
    "VORBEHANDLUNGSZEIT": 10,
    "PRI_AK_ID": 10026,
    "PRI_AK_LOT_ID": 10027,
    "PRI_AK_NAME": "Aurora B",
    "PRI_VERDUENNUNG": "1:25/1:50",
    "PRI_INKUBATIONSZEIT": "30",
    "SEK_AK_ID": 10028,
    "SEK_AK_LOT_ID": 10029,
    "SEK_AK_NAME": "Dako REAL Biotinylated 2nd AB",
    "SEK_INKUBATIONSZEIT": "20",
    "OPTI_HQ_LINKER_ZEIT": 8,
    "OPTI_HQ_MULTI_ZEIT": 8,
    "OPTI_PEROXIDASE_HEMMER": "nach",
    "BL_H2O2": false,
    "BL_AVIDIN_BIOTIN": false,
    "BL_BSA_NGS": false,
    "MATERIAL": "FFPE",
    "BEMERKUNGEN": "Dako Pen benutzt",
    "TA": "Person_10",
    "NICHT_BERECHNEN": false,
    "upsize_ts": "1CE1A3C8DF0B90DC"
  },
  {
    "FAERB_ID": 10030,
    "ProjektNr": "1842",
    "Folgeprojekt": "",
    "IHC_Schnitte": 6,
    "GEWEBE": "ohne Angabe",
    "IHC_Faerbegeraet": "Dako",
    "Etablierungslauf": true,
    "Faerbelauftyp": "Etablierungslauf (final)",
    "FAERBE_KIT": "Dako Real AEC",
    "REG_DATUM": "2020-11-18T00:00:00",
    "DEMASKIERUNG": "HIER",
    "REAGENZ": "Dako pH9",
    "VORBEHANDLUNGSZEIT": 10,
    "PRI_AK_ID": 10031,
    "PRI_AK_LOT_ID": 10032,
    "PRI_AK_NAME": "Aurora B/AIM1",
    "PRI_VERDUENNUNG": "1:25",
    "PRI_INKUBATIONSZEIT": "30",
    "SEK_AK_ID": 10028,
    "SEK_AK_LOT_ID": 10029,
    "SEK_AK_NAME": "Dako REAL Biotinylated 2nd AB",
    "SEK_VERDUENNUNG": "RTU",
    "SEK_INKUBATIONSZEIT": "20",
    "BL_H2O2": true,
    "BL_AVIDIN_BIOTIN": false,
    "BL_BSA_NGS": false,
    "NICHT_BERECHNEN": false,
    "upsize_ts": "B1906AC2E6B64419"
  },
  {
    "FAERB_ID": 10033,
    "ProjektNr": "1842",
    "Folgeprojekt": "",
    "IHC_Schnitte": 6,
    "GEWEBE": "ohne Angabe",
    "IHC_Faerbegeraet": "Dako",
    "Etablierungslauf": true,
    "Faerbelauftyp": "Etablierungslauf (final)",
    "FAERBE_KIT": "Dako Real AEC",
    "REG_DATUM": "2020-11-23T00:00:00",
    "DEMASKIERUNG": "HIER",
    "REAGENZ": "Dako pH9",
    "VORBEHANDLUNGSZEIT": 10,
    "PRI_AK_ID": 10031,
    "PRI_AK_LOT_ID": 10032,
    "PRI_AK_NAME": "Aurora B/AIM1",
    "PRI_VERDUENNUNG": "1:100",
    "PRI_INKUBATIONSZEIT": "30",
    "SEK_AK_ID": 10028,
    "SEK_AK_LOT_ID": 10029,
    "SEK_AK_NAME": "Dako REAL Biotinylated 2nd AB",
    "SEK_VERDUENNUNG": "RTU",
    "SEK_INKUBATIONSZEIT": "20",
    "BL_H2O2": true,
    "BL_AVIDIN_BIOTIN": false,
    "BL_BSA_NGS": false,
    "NICHT_BERECHNEN": false,
    "upsize_ts": "1ACE4D6E40155807"
  },
  {
    "FAERB_ID": 10014,
    "ProjektNr": "1842",
    "Folgeprojekt": "",
    "IHC_Schnitte": 2,
    "GEWEBE": "ohne Angabe",
    "IHC_Faerbegeraet": "Dako",
    "Etablierungslauf": true,
    "Faerbelauftyp": "Etablierungslauf (final)",
    "FAERBE_KIT": "Dako Real AEC",
    "REG_DATUM": "2020-11-25T00:00:00",
    "DEMASKIERUNG": "HIER",
    "REAGENZ": "Dako pH9",
    "VORBEHANDLUNGSZEIT": 10,
    "PRI_AK_ID": 10031,
    "PRI_AK_LOT_ID": 10032,
    "PRI_AK_NAME": "Aurora B/AIM1",
    "PRI_VERDUENNUNG": "1:50",
    "PRI_INKUBATIONSZEIT": "30",
    "SEK_AK_ID": 10028,
    "SEK_AK_LOT_ID": 10029,
    "SEK_AK_NAME": "Dako REAL Biotinylated 2nd AB",
    "SEK_VERDUENNUNG": "RTU",
    "SEK_INKUBATIONSZEIT": "20",
    "BL_H2O2": true,
    "BL_AVIDIN_BIOTIN": false,
    "BL_BSA_NGS": false,
    "NICHT_BERECHNEN": false,
    "upsize_ts": "11D3630D2E70DA21"
  },
  {
    "FAERB_ID": 10034,
    "ProjektNr": "1842",
    "Folgeprojekt": "",
    "IHC_Schnitte": 4,
    "GEWEBE": "ohne Angabe",
    "IHC_Faerbegeraet": "Ventana",
    "Etablierungslauf": true,
    "Faerbelauftyp": "Etablierungslauf (final)",
    "FAERBE_KIT": "OptiView DAB",
    "REG_DATUM": "2020-11-27T00:00:00",
    "DEMASKIERUNG": "HIER",
    "REAGENZ": "Ventana CC1",
    "VORBEHANDLUNGSZEIT": 64,
    "PRI_AK_ID": 10031,
    "PRI_AK_LOT_ID": 10032,
    "PRI_AK_NAME": "Aurora B/AIM1",
    "PRI_VERDUENNUNG": "1:10",
    "PRI_INKUBATIONSZEIT": "24",
    "OPTI_HQ_LINKER_ZEIT": 8,
    "OPTI_HQ_MULTI_ZEIT": 8,
    "OPTI_PEROXIDASE_HEMMER": "nach",
    "BL_H2O2": false,
    "BL_AVIDIN_BIOTIN": false,
    "BL_BSA_NGS": false,
    "NICHT_BERECHNEN": false,
    "upsize_ts": "6AB794A4178B0FD8"
  }
]';
?>
