<?php
header('Content-Type: application/json');
echo '[
    {
        "ORIGREC": 1,
        "ProjektNr_lang": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Projekttyp": "Studie_0001",
        "Bearbeitung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Abgabedatum": "2012-06-03T00:00:00",
        "a_ProbenAnzahl": 0,
        "b_AnzahlSchnitte": 0,
        "TMA-Nr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TMA-Schnitte": 0,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Arzt": "Mitarbeiter_030",
        "TA": "Mitarbeiter_031",
        "Aufgaben": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Projektstand": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Abschlusskontrolle": true,
        "Langzeitprojekt": false,
        "AB_Anforderung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_Projekttitel": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_P_Nachname_Vorname": "Mitarbeiter_032",
        "AB_P_Kundennummer": 38,
        "AB_Abgabe": "2012-06-03T00:00:00",
        "AB_Langzeitprojekt": false,
        "AB_Koop_Vorname_Nachname": "Mitarbeiter_033",
        "AB_P_weitere_Projektleiter": "Mitarbeiter_034",
        "AB_Bearbeitung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TimestampX": "AAAAAAA/5CU=",
        "AB_Rueckmeldung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_Genehmigung": "Anonymisierte Prozessbeschreibung für Testlauf."
    },
    {
        "ORIGREC": 2,
        "ProjektNr_lang": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Projekttyp": "Studie_0001",
        "Bearbeitung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Abgabedatum": "2011-05-18T00:00:00",
        "a_ProbenAnzahl": 15,
        "b_AnzahlSchnitte": 150,
        "TMA-Nr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TMA-Schnitte": 0,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Arzt": "Mitarbeiter_030",
        "TA": "Mitarbeiter_031",
        "Aufgaben": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Abschlusskontrolle": true,
        "Langzeitprojekt": false,
        "AB_Anforderung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_Projekttitel": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_P_Nachname_Vorname": "Mitarbeiter_032",
        "AB_P_Kundennummer": 38,
        "AB_Abgabe": "2011-05-18T00:00:00",
        "AB_Langzeitprojekt": false,
        "AB_Koop_Vorname_Nachname": "Mitarbeiter_033",
        "AB_P_weitere_Projektleiter": "Mitarbeiter_035",
        "AB_Bearbeitung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TimestampX": "AAAAAAA/5CY=",
        "AB_Rueckmeldung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_Genehmigung": "Anonymisierte Prozessbeschreibung für Testlauf."
    },
    {
        "ORIGREC": 3,
        "ProjektNr_lang": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Projekttyp": "Studie_0001",
        "Bearbeitung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Abgabedatum": "2011-04-26T00:00:00",
        "a_ProbenAnzahl": 0,
        "b_AnzahlSchnitte": 0,
        "TMA-Nr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TMA-Schnitte": 4,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Arzt": "Mitarbeiter_036",
        "TA": "Mitarbeiter_037",
        "Aufgaben": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Abschlusskontrolle": true,
        "Langzeitprojekt": false,
        "AB_Anforderung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_Projekttitel": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_P_Nachname_Vorname": "Mitarbeiter_038",
        "AB_P_Kundennummer": 259,
        "AB_Abgabe": "2011-04-26T00:00:00",
        "AB_Langzeitprojekt": false,
        "AB_Koop_Vorname_Nachname": "Mitarbeiter_039",
        "AB_P_weitere_Projektleiter": "Mitarbeiter_040",
        "AB_Bearbeitung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TimestampX": "AAAAAAA/5Cc=",
        "AB_Rueckmeldung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_Genehmigung": "Anonymisierte Prozessbeschreibung für Testlauf."
    },
    {
        "ORIGREC": 4,
        "ProjektNr_lang": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Projekttyp": "Studie_0001",
        "Bearbeitung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Abgabedatum": "2011-05-26T00:00:00",
        "a_ProbenAnzahl": 0,
        "b_AnzahlSchnitte": 0,
        "TMA-Schnitte": 0,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Arzt": "Mitarbeiter_041",
        "TA": "Mitarbeiter_037",
        "Aufgaben": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Abschlusskontrolle": true,
        "Langzeitprojekt": false,
        "AB_Anforderung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_Projekttitel": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_P_Nachname_Vorname": "Mitarbeiter_042",
        "AB_P_Kundennummer": 104,
        "AB_Abgabe": "2011-05-26T00:00:00",
        "AB_Langzeitprojekt": false,
        "AB_Koop_Vorname_Nachname": "Mitarbeiter_043",
        "AB_Bearbeitung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TimestampX": "AAAAAAA/5Cg=",
        "AB_Rueckmeldung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_Genehmigung": "Anonymisierte Prozessbeschreibung für Testlauf."
    },
    {
        "ORIGREC": 5,
        "ProjektNr_lang": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Projekttyp": "Studie_0001",
        "Bearbeitung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Abgabedatum": "2011-05-25T00:00:00",
        "a_ProbenAnzahl": 24,
        "b_AnzahlSchnitte": 240,
        "TMA-Nr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TMA-Schnitte": 0,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Arzt": "Mitarbeiter_044",
        "TA": "Mitarbeiter_031",
        "Aufgaben": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Abschlusskontrolle": true,
        "Langzeitprojekt": false,
        "AB_Anforderung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_Projekttitel": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_P_Nachname_Vorname": "Mitarbeiter_045",
        "AB_P_Kundennummer": 7,
        "AB_Abgabe": "2011-05-25T00:00:00",
        "AB_Langzeitprojekt": false,
        "AB_Koop_Vorname_Nachname": "Mitarbeiter_046",
        "AB_Bearbeitung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TimestampX": "AAAAAAA/5Ck=",
        "AB_Rueckmeldung": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "AB_Genehmigung": "Anonymisierte Prozessbeschreibung für Testlauf."
    }
]';
