<?php
header('Content-Type: application/json');
echo '[
  {
    "ORIGREC": 10019,
    "ProjektNr_lang": "0652",
    "Projekttyp": "NCT-TBB",
    "Bearbeitung": "abgeschlossen",
    "Abgabedatum": "2017-06-03T00:00:00",
    "a_ProbenAnzahl": 0,
    "b_AnzahlSchnitte": 0,
    "TMA-Nr": "0",
    "TMA-Schnitte": 0,
    "ProjektNr": "0652",
    "Arzt": "Person_25",
    "TA": "Person_26",
    "Aufgaben": "Mauslebern Kryo",
    "Projektstand": "Schnitte beim Antragssteller",
    "Abschlusskontrolle": true,
    "Langzeitprojekt": false,
    "AB_Anforderung": "Mausleber\r\n36 Proben, je 60T mit je 2 Schnitten \r\n(1/2 Methanol/1/2  Aceton fixiert)",
    "AB_Projekttitel": "Charakterisierung der PDGF B Maus II",
    "AB_P_Nachname_Vorname": "Person_27",
    "AB_P_Kundennummer": 38,
    "AB_Abgabe": "2017-06-03T00:00:00",
    "AB_Langzeitprojekt": false,
    "AB_Koop_Vorname_Nachname": "Person_28",
    "AB_P_weitere_Projektleiter": "Person_29",
    "AB_Bearbeitung": "abgeschlossen",
    "TimestampX": "488F43DB46FDD199",
    "AB_Rueckmeldung": "2016-04-21T00:00:00",
    "AB_Genehmigung": "Apr 21 2011 12:00AM"
  },
  {
    "ORIGREC": 10021,
    "ProjektNr_lang": "0653",
    "Projekttyp": "NCT-TBB",
    "Bearbeitung": "abgeschlossen",
    "Abgabedatum": "2016-05-18T00:00:00",
    "a_ProbenAnzahl": 15,
    "b_AnzahlSchnitte": 150,
    "TMA-Nr": "0",
    "TMA-Schnitte": 0,
    "ProjektNr": "0653",
    "Arzt": "Person_25",
    "TA": "Person_26",
    "Aufgaben": "Mauslebern kryo 15 Proben mit je 2 Schnitten (10OT)",
    "Abschlusskontrolle": true,
    "Langzeitprojekt": false,
    "AB_Anforderung": "Mauslebern (unfixiert) 15 Proben; \r\npro Probe 10 OT mitje 2 Schnitten",
    "AB_Projekttitel": "Charakterisierung d. PGPF B Transgenen Maus I",
    "AB_P_Nachname_Vorname": "Person_27",
    "AB_P_Kundennummer": 38,
    "AB_Abgabe": "2016-05-18T00:00:00",
    "AB_Langzeitprojekt": false,
    "AB_Koop_Vorname_Nachname": "Person_28",
    "AB_P_weitere_Projektleiter": "Person_30",
    "AB_Bearbeitung": "abgeschlossen",
    "TimestampX": "DACAA1AA00311A3C",
    "AB_Rueckmeldung": "2016-04-21T00:00:00",
    "AB_Genehmigung": "Apr 21 2011 12:00AM"
  },
  {
    "ORIGREC": 10023,
    "ProjektNr_lang": "0654",
    "Projekttyp": "NCT-TBB",
    "Bearbeitung": "abgeschlossen",
    "Abgabedatum": "2016-04-26T00:00:00",
    "a_ProbenAnzahl": 0,
    "b_AnzahlSchnitte": 0,
    "TMA-Nr": "45/1",
    "TMA-Schnitte": 4,
    "ProjektNr": "0654",
    "Arzt": "Person_31",
    "TA": "Person_32",
    "Aufgaben": "Array-Schnitte",
    "Abschlusskontrolle": true,
    "Langzeitprojekt": false,
    "AB_Anforderung": "Pan-Tumor-Array (je 4x)",
    "AB_Projekttitel": "Mastzellen im entzündlichen Infiltrat verschiedener Tumorentitäten",
    "AB_P_Nachname_Vorname": "Person_33",
    "AB_P_Kundennummer": 259,
    "AB_Abgabe": "2016-04-26T00:00:00",
    "AB_Langzeitprojekt": false,
    "AB_Koop_Vorname_Nachname": "Person_34",
    "AB_P_weitere_Projektleiter": "Person_35",
    "AB_Bearbeitung": "abgeschlossen",
    "TimestampX": "3016FB561421B162",
    "AB_Rueckmeldung": "2016-04-21T00:00:00",
    "AB_Genehmigung": "Apr 21 2011 12:00AM"
  },
  {
    "ORIGREC": 10024,
    "ProjektNr_lang": "0655",
    "Projekttyp": "NCT-TBB",
    "Bearbeitung": "abgeschlossen",
    "Abgabedatum": "2016-05-26T00:00:00",
    "a_ProbenAnzahl": 0,
    "b_AnzahlSchnitte": 0,
    "TMA-Schnitte": 0,
    "ProjektNr": "0655",
    "Arzt": "Person_36",
    "TA": "Person_32",
    "Aufgaben": "Array-Schnitte Augustin PAN-Array",
    "Abschlusskontrolle": true,
    "Langzeitprojekt": false,
    "AB_Anforderung": "5 Schnitte Pan NG-Array jeweils 4 versch. Blöcke \r\n5 Schnitte Pan Tumor-Array",
    "AB_Projekttitel": "Expressionsanalyse von Evi in humanen Gliomen",
    "AB_P_Nachname_Vorname": "Person_37",
    "AB_P_Kundennummer": 104,
    "AB_Abgabe": "2016-05-26T00:00:00",
    "AB_Langzeitprojekt": false,
    "AB_Koop_Vorname_Nachname": "Person_38",
    "AB_Bearbeitung": "abgeschlossen",
    "TimestampX": "2008656AFE237DCF",
    "AB_Rueckmeldung": "2016-04-26T00:00:00",
    "AB_Genehmigung": "Apr 25 2011 12:00AM"
  },
  {
    "ORIGREC": 10025,
    "ProjektNr_lang": "0656",
    "Projekttyp": "NCT-TBB",
    "Bearbeitung": "abgeschlossen",
    "Abgabedatum": "2016-05-25T00:00:00",
    "a_ProbenAnzahl": 24,
    "b_AnzahlSchnitte": 240,
    "TMA-Nr": "0",
    "TMA-Schnitte": 0,
    "ProjektNr": "0656",
    "Arzt": "Person_39",
    "TA": "Person_26",
    "Aufgaben": "Paraffin Schnitte kümmert sich selbst",
    "Abschlusskontrolle": true,
    "Langzeitprojekt": false,
    "AB_Anforderung": "40 Proben  (15 Melanome, 15 NZN, 10 dyspl. NZN)\r\nje 10 Schnitte/Probe",
    "AB_Projekttitel": "FAM 82C/A2  IHC an Melanomen, NZN, dyspl. NZN",
    "AB_P_Nachname_Vorname": "Person_40",
    "AB_P_Kundennummer": 7,
    "AB_Abgabe": "2016-05-25T00:00:00",
    "AB_Langzeitprojekt": false,
    "AB_Koop_Vorname_Nachname": "Person_41",
    "AB_Bearbeitung": "abgeschlossen",
    "TimestampX": "C573C9B4F4738B87",
    "AB_Rueckmeldung": "2016-04-26T00:00:00",
    "AB_Genehmigung": "Apr 25 2011 12:00AM"
  }
]';
?>
