<?php
header('Content-Type: application/json');
echo '[
    {
        "ORIGREC": 74,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "Folgeprojekt": "Anonymisierte_Daten_Dummy",
        "TMA_Name": "Anonymisierte_Daten_Dummy",
        "TMA_Nr": 52,
        "Blocknummern": "Anonymisierte_Daten_Dummy",
        "TMA_Duplikate": 3.0,
        "TMA_Anz_Stanzen_pro_Bl": 112.0,
        "TMA_Anz_Patienten": 224,
        "TMA_Anz_HE_Schnitte": 224,
        "Bemerkung": "Anonymisierte_Daten_Dummy",
        "Ausgeschieden": false,
        "Datum": "2009-05-01T00:00:00",
        "TimestampX": "AAAAAAABTDQ="
    },
    {
        "ORIGREC": 77,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TMA_Name": "Anonymisierte_Daten_Dummy",
        "TMA_Nr": 1011,
        "Blocknummern": "Anonymisierte_Daten_Dummy",
        "TMA_Duplikate": 1.0,
        "TMA_Anz_Stanzen_pro_Bl": 50.0,
        "TMA_Anz_Patienten": 50,
        "TMA_Anz_HE_Schnitte": 50,
        "Bemerkung": "Anonymisierte_Daten_Dummy",
        "Ausgeschieden": false,
        "Datum": "2007-03-20T00:00:00",
        "TimestampX": "AAAAAAAAMUo="
    },
    {
        "ORIGREC": 79,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TMA_Name": "Anonymisierte_Daten_Dummy",
        "TMA_Nr": 1010,
        "Blocknummern": "Anonymisierte_Daten_Dummy",
        "TMA_Duplikate": 1.0,
        "TMA_Anz_Stanzen_pro_Bl": 70.0,
        "TMA_Anz_Patienten": 140,
        "TMA_Anz_HE_Schnitte": 140,
        "Bemerkung": "Anonymisierte_Daten_Dummy",
        "Ausgeschieden": false,
        "Datum": "2007-03-20T00:00:00",
        "TimestampX": "AAAAAAAAMUs="
    },
    {
        "ORIGREC": 86,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TMA_Name": "Anonymisierte_Daten_Dummy",
        "TMA_Nr": 1015,
        "Blocknummern": "Anonymisierte_Daten_Dummy",
        "TMA_Duplikate": 1.0,
        "TMA_Anz_Stanzen_pro_Bl": 60.0,
        "TMA_Anz_Patienten": 12,
        "TMA_Anz_HE_Schnitte": 12,
        "Bemerkung": "Anonymisierte_Daten_Dummy",
        "Ausgeschieden": false,
        "Datum": "2007-04-13T00:00:00",
        "TimestampX": "AAAAAAAAMUw="
    },
    {
        "ORIGREC": 238,
        "ProjektNr": "Anonymisierte Prozessbeschreibung für Testlauf.",
        "TMA_Name": "Anonymisierte_Daten_Dummy",
        "TMA_Nr": 36,
        "Blocknummern": "Anonymisierte_Daten_Dummy",
        "TMA_Duplikate": 3.0,
        "TMA_Anz_Stanzen_pro_Bl": 185.0,
        "TMA_Anz_Patienten": 37,
        "TMA_Anz_HE_Schnitte": 37,
        "Bemerkung": "Anonymisierte_Daten_Dummy",
        "Ausgeschieden": false,
        "Datum": "2008-11-06T00:00:00",
        "TimestampX": "AAAAAAAAMU0="
    }
]';
